<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Product;
use App\Models\Supplier;

class DemoDataSeeder extends Seeder
{
    public function run(): void
    {
        // ==================== Categories ====================
        $categories = [
            ['name' => 'Electronics', 'slug' => 'electronics', 'icon' => 'fas fa-laptop', 'sort_order' => 1],
            ['name' => 'Fashion', 'slug' => 'fashion', 'icon' => 'fas fa-tshirt', 'sort_order' => 2],
            ['name' => 'Home & Living', 'slug' => 'home-living', 'icon' => 'fas fa-couch', 'sort_order' => 3],
            ['name' => 'Beauty', 'slug' => 'beauty', 'icon' => 'fas fa-spa', 'sort_order' => 4],
            ['name' => 'Sports', 'slug' => 'sports', 'icon' => 'fas fa-dumbbell', 'sort_order' => 5],
            ['name' => 'Books', 'slug' => 'books', 'icon' => 'fas fa-book', 'sort_order' => 6],
            ['name' => 'Toys', 'slug' => 'toys', 'icon' => 'fas fa-puzzle-piece', 'sort_order' => 7],
            ['name' => 'Groceries', 'slug' => 'groceries', 'icon' => 'fas fa-shopping-basket', 'sort_order' => 8],
        ];

        $createdCategories = [];
        foreach ($categories as $cat) {
            $createdCategories[] = Category::create(array_merge($cat, [
                'status' => true,
                'description' => "Shop the best {$cat['name']} products at unbeatable prices.",
            ]));
        }

        // ==================== Brands ====================
        $brands = [
            ['name' => 'Apple', 'slug' => 'apple', 'sort_order' => 1],
            ['name' => 'Samsung', 'slug' => 'samsung', 'sort_order' => 2],
            ['name' => 'Nike', 'slug' => 'nike', 'sort_order' => 3],
            ['name' => 'Adidas', 'slug' => 'adidas', 'sort_order' => 4],
            ['name' => 'Sony', 'slug' => 'sony', 'sort_order' => 5],
            ['name' => 'LG', 'slug' => 'lg', 'sort_order' => 6],
        ];

        $createdBrands = [];
        foreach ($brands as $brand) {
            $createdBrands[] = Brand::create(array_merge($brand, [
                'status' => true,
                'description' => "Official {$brand['name']} products.",
            ]));
        }

        // ==================== Suppliers ====================
        $suppliers = [
            [
                'name' => 'TechSource Global',
                'company_name' => 'TechSource Global Inc.',
                'contact_person' => 'James Wilson',
                'email' => 'james@techsource.com',
                'phone' => '+1 (415) 555-0101',
                'alternative_phone' => '+1 (415) 555-0102',
                'website' => 'https://techsource.com',
                'trade_license_number' => 'TL-2023-USA-001',
                'tax_vat_number' => 'VAT-US-98765432',
                'country' => 'United States',
                'state' => 'California',
                'city' => 'San Francisco',
                'postal_code' => '94105',
                'full_address' => '123 Market Street, Suite 400, San Francisco, CA 94105',
                'payment_terms' => 'Net 30',
                'credit_limit' => 50000.00,
                'currency' => 'USD',
                'outstanding_balance' => 12500.00,
                'last_purchase_date' => now()->subDays(5),
                'status' => 'active',
            ],
            [
                'name' => 'Fashion Distributors Ltd',
                'company_name' => 'Fashion Distributors Ltd.',
                'contact_person' => 'Sarah Chen',
                'email' => 'sarah@fashiondist.com',
                'phone' => '+1 (212) 555-0202',
                'website' => 'https://fashiondist.com',
                'trade_license_number' => 'TL-2024-NY-045',
                'tax_vat_number' => 'VAT-US-45678901',
                'country' => 'United States',
                'state' => 'New York',
                'city' => 'New York',
                'postal_code' => '10001',
                'full_address' => '456 Fashion Avenue, Floor 12, New York, NY 10001',
                'payment_terms' => 'Net 45',
                'credit_limit' => 35000.00,
                'currency' => 'USD',
                'outstanding_balance' => 8900.00,
                'last_purchase_date' => now()->subDays(12),
                'status' => 'active',
            ],
            [
                'name' => 'HomeGoods Wholesale',
                'company_name' => 'HomeGoods Wholesale GmbH',
                'contact_person' => 'Klaus Mueller',
                'email' => 'klaus@homegoods.de',
                'phone' => '+49 30 555-0303',
                'website' => 'https://homegoods.de',
                'trade_license_number' => 'TL-2024-DE-112',
                'tax_vat_number' => 'VAT-DE-123456789',
                'country' => 'Germany',
                'state' => 'Berlin',
                'city' => 'Berlin',
                'full_address' => 'Alexanderplatz 15, 10178 Berlin, Germany',
                'payment_terms' => 'Net 60',
                'credit_limit' => 25000.00,
                'currency' => 'EUR',
                'outstanding_balance' => 3200.00,
                'status' => 'active',
            ],
            [
                'name' => 'BeautyPlus Supplies',
                'company_name' => 'BeautyPlus Supplies Co.',
                'contact_person' => 'Maria Garcia',
                'email' => 'maria@beautyplus.com',
                'phone' => '+34 91 555-0404',
                'country' => 'Spain',
                'state' => 'Madrid',
                'city' => 'Madrid',
                'full_address' => 'Calle Mayor 23, 28013 Madrid, Spain',
                'payment_terms' => 'Net 30',
                'credit_limit' => 15000.00,
                'currency' => 'EUR',
                'outstanding_balance' => 0.00,
                'last_purchase_date' => now()->subDays(30),
                'status' => 'inactive',
            ],
            [
                'name' => 'Sports Gear International',
                'company_name' => 'Sports Gear International Ltd',
                'contact_person' => 'David Park',
                'email' => 'david@sportsgear.com',
                'phone' => '+44 20 555-0505',
                'website' => 'https://sportsgear.com',
                'trade_license_number' => 'TL-2023-UK-789',
                'tax_vat_number' => 'VAT-GB-456789012',
                'country' => 'United Kingdom',
                'state' => 'England',
                'city' => 'London',
                'postal_code' => 'EC2A 4NE',
                'full_address' => '88 Sports Way, Shoreditch, London EC2A 4NE',
                'payment_terms' => 'Net 45',
                'credit_limit' => 40000.00,
                'currency' => 'GBP',
                'outstanding_balance' => 18750.00,
                'last_purchase_date' => now()->subDays(3),
                'status' => 'active',
            ],
            [
                'name' => 'ToyWorld Manufacturing',
                'company_name' => 'ToyWorld Manufacturing Pvt Ltd',
                'contact_person' => 'Raj Patel',
                'email' => 'raj@toyworld.in',
                'phone' => '+91 22 555-0606',
                'country' => 'India',
                'state' => 'Maharashtra',
                'city' => 'Mumbai',
                'full_address' => '42 Industrial Zone, Andheri East, Mumbai 400093',
                'payment_terms' => 'Due on Receipt',
                'credit_limit' => 10000.00,
                'currency' => 'INR',
                'outstanding_balance' => 0.00,
                'status' => 'active',
            ],
        ];

        $createdSuppliers = [];
        foreach ($suppliers as $supplier) {
            $createdSuppliers[] = Supplier::firstOrCreate(
                ['email' => $supplier['email']],
                $supplier
            );
        }

        // ==================== Products ====================
        $products = [
            // Electronics - Featured
            [
                'name' => 'iPhone 15 Pro Max',
                'slug' => 'iphone-15-pro-max',
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $createdBrands[0]->id,
                'price' => 1199.00,
                'discount' => 10,
                'discount_type' => 'percentage',
                'stock' => 50,
                'status' => 'active',
                'featured' => true,
                'best_seller' => true,
                'description' => 'The most powerful iPhone ever with A17 Pro chip, titanium design, and advanced camera system.',
                'short_description' => 'Apple iPhone 15 Pro Max - Titanium, A17 Pro Chip',
                'specifications' => ['Storage' => '256GB', 'Display' => '6.7 inch', 'Chip' => 'A17 Pro'],
            ],
            [
                'name' => 'Samsung Galaxy S24 Ultra',
                'slug' => 'samsung-galaxy-s24-ultra',
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $createdBrands[1]->id,
                'price' => 1099.00,
                'discount' => 15,
                'discount_type' => 'percentage',
                'stock' => 35,
                'status' => 'active',
                'featured' => true,
                'best_seller' => true,
                'description' => 'Galaxy AI is here. Search like never before, effortlessly edit photos, and summarize lectures with ease.',
                'short_description' => 'Samsung Galaxy S24 Ultra - AI Powered',
                'specifications' => ['Storage' => '512GB', 'Display' => '6.8 inch', 'RAM' => '12GB'],
            ],
            [
                'name' => 'MacBook Air M3',
                'slug' => 'macbook-air-m3',
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $createdBrands[0]->id,
                'price' => 1099.00,
                'discount' => 0,
                'stock' => 25,
                'status' => 'active',
                'featured' => true,
                'description' => 'Supercharged by M3. With a stunning Liquid Retina display and up to 18 hours of battery life.',
                'short_description' => 'Apple MacBook Air M3 - 13 inch',
                'specifications' => ['Chip' => 'M3', 'RAM' => '8GB', 'Storage' => '256GB SSD'],
            ],
            [
                'name' => 'Sony WH-1000XM5',
                'slug' => 'sony-wh-1000xm5',
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $createdBrands[4]->id,
                'price' => 349.99,
                'discount' => 20,
                'discount_type' => 'percentage',
                'stock' => 60,
                'status' => 'active',
                'featured' => true,
                'best_seller' => true,
                'description' => 'Industry-leading noise cancellation with Auto NC Optimizer. Crystal clear hands-free calling.',
                'short_description' => 'Sony Wireless Noise Canceling Headphones',
                'specifications' => ['Type' => 'Over-ear', 'Battery' => '30 hours', 'ANC' => 'Yes'],
            ],
            [
                'name' => 'LG OLED 55" TV',
                'slug' => 'lg-oled-55-tv',
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $createdBrands[5]->id,
                'price' => 1299.00,
                'discount' => 200,
                'discount_type' => 'fixed',
                'stock' => 15,
                'status' => 'active',
                'featured' => true,
                'description' => 'Self-lit OLED pixels deliver perfect blacks and over a billion colors. α9 AI Processor 4K Gen6.',
                'short_description' => 'LG 55 inch OLED 4K Smart TV',
                'specifications' => ['Size' => '55 inch', 'Resolution' => '4K', 'HDR' => 'Dolby Vision'],
            ],

            // Fashion - Best Sellers
            [
                'name' => 'Nike Air Max 270',
                'slug' => 'nike-air-max-270',
                'category_id' => $createdCategories[1]->id,
                'brand_id' => $createdBrands[2]->id,
                'price' => 150.00,
                'discount' => 25,
                'discount_type' => 'percentage',
                'stock' => 100,
                'status' => 'active',
                'best_seller' => true,
                'description' => 'The biggest Max Air unit yet brings unmatched comfort to your everyday style.',
                'short_description' => 'Nike Air Max 270 - Men\'s Shoes',
                'specifications' => ['Type' => 'Sneakers', 'Upper' => 'Mesh', 'Sole' => 'Rubber'],
            ],
            [
                'name' => 'Adidas Ultraboost',
                'slug' => 'adidas-ultraboost',
                'category_id' => $createdCategories[1]->id,
                'brand_id' => $createdBrands[3]->id,
                'price' => 180.00,
                'discount' => 0,
                'stock' => 75,
                'status' => 'active',
                'best_seller' => true,
                'description' => 'Energy-returning running shoes with a responsive BOOST midsole and Primeknit+ upper.',
                'short_description' => 'Adidas Ultraboost - Running Shoes',
                'specifications' => ['Type' => 'Running', 'Upper' => 'Primeknit', 'Midsole' => 'BOOST'],
            ],
            [
                'name' => 'Classic Denim Jacket',
                'slug' => 'classic-denim-jacket',
                'category_id' => $createdCategories[1]->id,
                'brand_id' => null,
                'price' => 89.99,
                'discount' => 10,
                'discount_type' => 'fixed',
                'stock' => 50,
                'status' => 'active',
                'featured' => true,
                'description' => 'Timeless denim jacket crafted from premium cotton. A wardrobe essential for all seasons.',
                'short_description' => 'Premium Denim Jacket - Unisex',
                'specifications' => ['Material' => '100% Cotton', 'Fit' => 'Regular', 'Care' => 'Machine Wash'],
            ],
            [
                'name' => 'Running Shorts Pro',
                'slug' => 'running-shorts-pro',
                'category_id' => $createdCategories[1]->id,
                'brand_id' => $createdBrands[2]->id,
                'price' => 45.00,
                'discount' => 0,
                'stock' => 120,
                'status' => 'active',
                'description' => 'Lightweight running shorts with Dri-FIT technology to keep you dry and comfortable.',
                'short_description' => 'Nike Dri-FIT Running Shorts',
                'specifications' => ['Material' => 'Polyester', 'Length' => '7 inch', 'Pockets' => '2'],
            ],

            // Home & Living
            [
                'name' => 'Minimalist Desk Lamp',
                'slug' => 'minimalist-desk-lamp',
                'category_id' => $createdCategories[2]->id,
                'brand_id' => null,
                'price' => 59.99,
                'discount' => 15,
                'discount_type' => 'percentage',
                'stock' => 40,
                'status' => 'active',
                'featured' => true,
                'description' => 'Modern LED desk lamp with adjustable brightness and color temperature. Touch control.',
                'short_description' => 'LED Desk Lamp - Adjustable Brightness',
                'specifications' => ['Bulb' => 'LED', 'Wattage' => '12W', 'Control' => 'Touch'],
            ],
            [
                'name' => 'Cozy Throw Blanket',
                'slug' => 'cozy-throw-blanket',
                'category_id' => $createdCategories[2]->id,
                'brand_id' => null,
                'price' => 39.99,
                'discount' => 0,
                'stock' => 80,
                'status' => 'active',
                'description' => 'Ultra-soft fleece throw blanket perfect for couch, bed, or travel. Machine washable.',
                'short_description' => 'Soft Fleece Throw Blanket',
                'specifications' => ['Material' => 'Fleece', 'Size' => '150x200cm', 'Weight' => '0.8kg'],
            ],
            [
                'name' => 'Ceramic Plant Pot Set',
                'slug' => 'ceramic-plant-pot-set',
                'category_id' => $createdCategories[2]->id,
                'brand_id' => null,
                'price' => 34.99,
                'discount' => 5,
                'discount_type' => 'fixed',
                'stock' => 60,
                'status' => 'active',
                'description' => 'Set of 3 handmade ceramic plant pots in matte finish. Drainage holes included.',
                'short_description' => '3-Pack Ceramic Plant Pots',
                'specifications' => ['Material' => 'Ceramic', 'Sizes' => 'S/M/L', 'Drainage' => 'Yes'],
            ],

            // Beauty
            [
                'name' => 'Vitamin C Serum',
                'slug' => 'vitamin-c-serum',
                'category_id' => $createdCategories[3]->id,
                'brand_id' => null,
                'price' => 29.99,
                'discount' => 20,
                'discount_type' => 'percentage',
                'stock' => 90,
                'status' => 'active',
                'best_seller' => true,
                'description' => 'Brightening vitamin C serum with hyaluronic acid. Reduces dark spots and boosts collagen.',
                'short_description' => 'Vitamin C + Hyaluronic Acid Serum',
                'specifications' => ['Volume' => '30ml', 'Skin Type' => 'All', 'Key Ingredient' => 'Vitamin C'],
            ],
            [
                'name' => 'Matte Lipstick Collection',
                'slug' => 'matte-lipstick-collection',
                'category_id' => $createdCategories[3]->id,
                'brand_id' => null,
                'price' => 24.99,
                'discount' => 0,
                'stock' => 70,
                'status' => 'active',
                'featured' => true,
                'description' => 'Set of 6 long-lasting matte lipsticks in trending shades. Hydrating formula.',
                'short_description' => '6-Color Matte Lipstick Set',
                'specifications' => ['Colors' => '6', 'Finish' => 'Matte', 'Lasting' => '8 hours'],
            ],

            // Sports
            [
                'name' => 'Yoga Mat Premium',
                'slug' => 'yoga-mat-premium',
                'category_id' => $createdCategories[4]->id,
                'brand_id' => null,
                'price' => 49.99,
                'discount' => 10,
                'discount_type' => 'percentage',
                'stock' => 55,
                'status' => 'active',
                'description' => 'Extra thick non-slip yoga mat with carrying strap. Eco-friendly TPE material.',
                'short_description' => 'Non-Slip TPE Yoga Mat 6mm',
                'specifications' => ['Thickness' => '6mm', 'Material' => 'TPE', 'Size' => '183x61cm'],
            ],
            [
                'name' => 'Adjustable Dumbbells',
                'slug' => 'adjustable-dumbbells',
                'category_id' => $createdCategories[4]->id,
                'brand_id' => null,
                'price' => 199.99,
                'discount' => 30,
                'discount_type' => 'fixed',
                'stock' => 20,
                'status' => 'active',
                'best_seller' => true,
                'description' => 'Space-saving adjustable dumbbells from 5 to 25 lbs. Quick-change weight selection.',
                'short_description' => '5-25 lb Adjustable Dumbbell Pair',
                'specifications' => ['Weight Range' => '5-25 lbs', 'Increments' => '5 lbs', 'Grip' => 'Non-slip'],
            ],

            // Books
            [
                'name' => 'The Art of Programming',
                'slug' => 'the-art-of-programming',
                'category_id' => $createdCategories[5]->id,
                'brand_id' => null,
                'price' => 39.99,
                'discount' => 0,
                'stock' => 200,
                'status' => 'active',
                'description' => 'A comprehensive guide to modern software development. From basics to advanced patterns.',
                'short_description' => 'Modern Software Development Guide',
                'specifications' => ['Pages' => '450', 'Format' => 'Paperback', 'Language' => 'English'],
            ],

            // Toys
            [
                'name' => 'Building Blocks Set',
                'slug' => 'building-blocks-set',
                'category_id' => $createdCategories[6]->id,
                'brand_id' => null,
                'price' => 29.99,
                'discount' => 15,
                'discount_type' => 'percentage',
                'stock' => 100,
                'status' => 'active',
                'featured' => true,
                'description' => '500-piece colorful building blocks set. Compatible with major brands. Ages 4+.',
                'short_description' => '500pc Building Blocks - Kids',
                'specifications' => ['Pieces' => '500', 'Age' => '4+', 'Material' => 'ABS Plastic'],
            ],

            // More Electronics - Flash Sale
            [
                'name' => 'Wireless Earbuds Pro',
                'slug' => 'wireless-earbuds-pro',
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $createdBrands[4]->id,
                'price' => 79.99,
                'discount' => 40,
                'discount_type' => 'percentage',
                'stock' => 150,
                'status' => 'active',
                'featured' => true,
                'best_seller' => true,
                'description' => 'True wireless earbuds with active noise cancellation and 30-hour total battery life.',
                'short_description' => 'Sony WF-C700N Wireless Earbuds',
                'specifications' => ['Battery' => '30 hours total', 'ANC' => 'Yes', 'IP Rating' => 'IPX4'],
            ],
            [
                'name' => 'Smart Watch Series 9',
                'slug' => 'smart-watch-series-9',
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $createdBrands[0]->id,
                'price' => 399.00,
                'discount' => 50,
                'discount_type' => 'fixed',
                'stock' => 45,
                'status' => 'active',
                'featured' => true,
                'best_seller' => true,
                'description' => 'Advanced health monitoring, GPS, and always-on display. Water resistant to 50m.',
                'short_description' => 'Apple Watch Series 9 - GPS',
                'specifications' => ['Display' => 'Always-on', 'Water Resistance' => '50m', 'GPS' => 'Yes'],
            ],
            [
                'name' => 'Portable Bluetooth Speaker',
                'slug' => 'portable-bluetooth-speaker',
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $createdBrands[1]->id,
                'price' => 69.99,
                'discount' => 30,
                'discount_type' => 'percentage',
                'stock' => 80,
                'status' => 'active',
                'best_seller' => true,
                'description' => '360-degree sound with deep bass. IP67 waterproof and dustproof. 24-hour playtime.',
                'short_description' => 'Samsung Portable Speaker 360',
                'specifications' => ['Battery' => '24 hours', 'Waterproof' => 'IP67', 'Bluetooth' => '5.3'],
            ],
        ];

        foreach ($products as $product) {
            Product::create(array_merge($product, [
                'sku' => 'SKU-' . strtoupper(uniqid()),
                'cost_price' => $product['price'] * 0.6,
                'low_stock_threshold' => 10,
                'published_at' => now(),
            ]));
        }
    }
}
